# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesort',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='第一分类'),
        ),
        migrations.AddField(
            model_name='course',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseSort', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='buy',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
