# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180425_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='coursesort',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseClass', verbose_name='第一分类'),
        ),
    ]
