# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='手机号码'),
        ),
    ]
