# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180427_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverify',
            options={'verbose_name': '验证', 'verbose_name_plural': '验证'},
        ),
    ]
